<?php

namespace App\Repository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends \Doctrine\ORM\EntityRepository
{
    public function showDays()
    {
        $today= new \DateTime();
        $end = new \DateTime();
        $end->add(new \DateInterval('P6M'));
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.day BETWEEN :start AND :end')
        ->setParameter('start', $today->format('Y-m-d')) 
        ->setParameter('end',  $end->format('Y-m-d'))
        ->orderBy('c.day', 'DESC');

        return $qb->getQuery()->getArrayResult();
    }
}
